image: bjodah/dockerfile-bjodah-scicomp
git:
    path: github.com/bjodah/batemaneq
script:
  - if [[ "$DRONE_BRANCH" =~ ^v[0-9]+.[0-9]?* ]]; then export BATEMANEQ_RELEASE_VERSION=$DRONE_BRANCH; echo ${BATEMANEQ_RELEASE_VERSION} | tail -c +2 > __conda_version__.txt; fi
  - python2 setup.py build_ext --inplace
  - python3 setup.py build_ext --inplace
  - PYTHONPATH=$(pwd) python2 -m pytest
  - PYTHONPATH=$(pwd) python3 -m pytest
  - pep8 .
  - python2 -m doctest README.rst
  - python2 setup.py sdist
  - scp dist/* batemaneq@hera.physchem.kth.se:~/public_html/
