build:
  image: bjodah/bjodahimg16:v1.2
  commands:
    - ./scripts/ci.sh
    - (cd examples/; ipython2 nbconvert --to=html --ExecutePreprocessor.enabled=True --ExecutePreprocessor.timeout=300 *.ipynb)
    - (cd examples/; ../scripts/render_index.sh *.html)
    - python3 -m pip install sphinx sphinx_rtd_theme
    - ./scripts/generate_docs.sh
    - ./scripts/prepare_deploy.sh

deploy:

  rsync:
    host: hera.physchem.kth.se
    user: batemaneq
    port: 22
    source: deploy/
    target: ~
    recursive: true
    delete: false
