{% set name = "batemaneq" %}
{% set version = "0.3.0+git" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  number: 0

requirements:
  build:
    - python
    - numpy
    - cython
  run:
    - python
    - numpy

test:
  imports:
    - {{ name }}
  requires:
    - pytest
    - boost
    - cython
    - scipy
  commands:
    - python -m pytest --pyargs {{ name }}

about:
  home: https://github.com/bjodah/{{ name }}
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'batemaneq provides a Python package for evaluating the Bateman equation'
  doc_url: https://bjodah.github.io/{{ name }}/latest

extra:
  recipe-maintainers:
    - bjodah
