package:
  name: batemaneq
  version: 0.1.0.git

source:
  path: ../

build:
  number: 0

requirements:
  build:
    - python
    - numpy
    - cython
  run:
    - numpy
    - python


test:
  requires:
    - python
    - boost  # multiprecision
    - cython

  imports:
    - batemaneq

about:
  home: https://github.com/bjodah/batemaneq
  license: Simplified BSD license
